/**
 * Inert DESEN Neutral Web starter contracts and declarative Source templates.
 * Executable adapters are available only through the explicit `./react-adapters` subpath.
 * @packageDocumentation
 */
export {
  STARTER_BOX_CAPABILITY_ID,
  STARTER_BUTTON_CAPABILITY_ID,
  STARTER_CARD_CAPABILITY_ID,
  STARTER_BADGE_CAPABILITY_ID,
  STARTER_AVATAR_CAPABILITY_ID,
  STARTER_ALERT_CAPABILITY_ID,
  STARTER_LIST_CAPABILITY_ID,
  STARTER_TABLE_CAPABILITY_ID,
  STARTER_SKELETON_CAPABILITY_ID,
  STARTER_PROGRESS_CAPABILITY_ID,
  STARTER_DATA_DISPLAY_MAX_ITEMS,
  STARTER_TABLE_MAX_COLUMNS,
  STARTER_CATALOG_ID,
  STARTER_CATALOG_TARGET,
  STARTER_CATALOG_TEMPLATE,
  STARTER_CATALOG_VERSION,
  STARTER_CHECKBOX_CAPABILITY_ID,
  STARTER_COMBOBOX_CAPABILITY_ID,
  STARTER_COMPONENT_REGISTRATIONS,
  STARTER_DIALOG_CAPABILITY_ID,
  STARTER_DIALOG_CONTENT_MAX_ITEMS,
  STARTER_ACCORDION_CAPABILITY_ID,
  STARTER_DISCLOSURE_MAX_ITEMS,
  STARTER_MENU_CAPABILITY_ID,
  STARTER_OVERLAY_CONTENT_MAX_ITEMS,
  STARTER_POPOVER_CAPABILITY_ID,
  STARTER_TOOLTIP_CAPABILITY_ID,
  STARTER_GRID_CAPABILITY_ID,
  STARTER_HEADING_CAPABILITY_ID,
  STARTER_ICON_CAPABILITY_ID,
  STARTER_IMAGE_CAPABILITY_ID,
  STARTER_LAYOUT_CONTENT_MAX_ITEMS,
  STARTER_NUMBER_FIELD_CAPABILITY_ID,
  STARTER_NUMERIC_MAX_STEP,
  STARTER_NUMERIC_MAXIMUM,
  STARTER_NUMERIC_MINIMUM,
  STARTER_RADIO_GROUP_CAPABILITY_ID,
  STARTER_RADIO_GROUP_MAX_OPTIONS,
  STARTER_SELECT_CAPABILITY_ID,
  STARTER_SELECT_MAX_OPTIONS,
  STARTER_SELECTION_MAX_OPTIONS,
  STARTER_SEPARATOR_CAPABILITY_ID,
  STARTER_SLIDER_CAPABILITY_ID,
  STARTER_STACK_CAPABILITY_ID,
  STARTER_SWITCH_CAPABILITY_ID,
  STARTER_TABS_CAPABILITY_ID,
  STARTER_TABS_MAX_ITEMS,
  STARTER_TEXT_AREA_CAPABILITY_ID,
  STARTER_TEXT_CAPABILITY_ID,
  STARTER_TEXT_FIELD_CAPABILITY_ID,
  starterBoxComponentRegistration,
  starterButtonComponentRegistration,
  starterCardComponentRegistration,
  starterBadgeComponentRegistration,
  starterAvatarComponentRegistration,
  starterAlertComponentRegistration,
  starterListComponentRegistration,
  starterTableComponentRegistration,
  starterSkeletonComponentRegistration,
  starterProgressComponentRegistration,
  starterCheckboxComponentRegistration,
  starterComboboxComponentRegistration,
  starterDialogComponentRegistration,
  starterAccordionComponentRegistration,
  starterMenuComponentRegistration,
  starterPopoverComponentRegistration,
  starterTooltipComponentRegistration,
  starterGridComponentRegistration,
  starterHeadingComponentRegistration,
  starterIconComponentRegistration,
  starterImageComponentRegistration,
  starterNumberFieldComponentRegistration,
  starterRadioGroupComponentRegistration,
  starterSelectComponentRegistration,
  starterSeparatorComponentRegistration,
  starterSliderComponentRegistration,
  starterStackComponentRegistration,
  starterSwitchComponentRegistration,
  starterTabsComponentRegistration,
  starterTextAreaComponentRegistration,
  starterTextComponentRegistration,
  starterTextFieldComponentRegistration,
} from "./contracts.js";
export type {
  StarterBoxProps,
  StarterButtonProps,
  StarterCardProps,
  StarterBadgeProps,
  StarterAvatarProps,
  StarterAlertProps,
  StarterListProps,
  StarterTableProps,
  StarterTableColumn,
  StarterTableRow,
  StarterSkeletonProps,
  StarterProgressProps,
  StarterCheckboxProps,
  StarterComboboxOption,
  StarterComboboxProps,
  StarterDialogProps,
  StarterAccordionProps,
  StarterDisclosureItem,
  StarterMenuProps,
  StarterPopoverProps,
  StarterTooltipProps,
  StarterGridProps,
  StarterHeadingProps,
  StarterIconProps,
  StarterImageProps,
  StarterNumberFieldProps,
  StarterRadioGroupOption,
  StarterRadioGroupProps,
  StarterSelectOption,
  StarterSelectProps,
  StarterSeparatorProps,
  StarterSliderProps,
  StarterStackProps,
  StarterSwitchProps,
  StarterTab,
  StarterTabsProps,
  StarterTextAreaProps,
  StarterTextFieldProps,
  StarterTextProps,
} from "./contracts.js";
export {
  isStarterCapabilityVisualStyleValue,
  isStarterVisualStyleValue,
  starterVisualStyleProfileForCapability,
} from "./visual-style-profile.js";
export type { StarterVisualStyleProfile } from "./visual-style-profile.js";
export {
  createStarterNodeTemplate,
  STARTER_TEMPLATE_ID_PREFIX_MAX_LENGTH,
  STARTER_TEMPLATE_MAX_RESERVED_IDS,
} from "./templates.js";
export type {
  CreateStarterNodeTemplateInput,
  StarterSourceNode,
  StarterTemplateCapabilityId,
} from "./templates.js";
