/**
 * Inert DESEN Neutral Web starter contracts and declarative Source templates.
 * Executable adapters are available only through the explicit `./react-adapters` subpath.
 * @packageDocumentation
 */
export {
  STARTER_CATALOG_ID,
  STARTER_CATALOG_VERSION,
  STARTER_CATALOG_TARGET,
  STARTER_CATALOG_TEMPLATE,
  STARTER_BUTTON_CAPABILITY_ID,
  STARTER_BOX_CAPABILITY_ID,
  STARTER_SELECT_CAPABILITY_ID,
  STARTER_CHECKBOX_CAPABILITY_ID,
  STARTER_DIALOG_CAPABILITY_ID,
  STARTER_GRID_CAPABILITY_ID,
  STARTER_HEADING_CAPABILITY_ID,
  STARTER_ICON_CAPABILITY_ID,
  STARTER_IMAGE_CAPABILITY_ID,
  STARTER_RADIO_GROUP_CAPABILITY_ID,
  STARTER_RADIO_GROUP_MAX_OPTIONS,
  STARTER_LAYOUT_CONTENT_MAX_ITEMS,
  STARTER_SEPARATOR_CAPABILITY_ID,
  STARTER_STACK_CAPABILITY_ID,
  STARTER_SWITCH_CAPABILITY_ID,
  STARTER_TEXT_AREA_CAPABILITY_ID,
  STARTER_TEXT_CAPABILITY_ID,
  STARTER_TEXT_FIELD_CAPABILITY_ID,
  STARTER_SELECT_MAX_OPTIONS,
  STARTER_DIALOG_CONTENT_MAX_ITEMS,
  STARTER_COMPONENT_REGISTRATIONS,
  starterButtonComponentRegistration,
  starterBoxComponentRegistration,
  starterSelectComponentRegistration,
  starterCheckboxComponentRegistration,
  starterDialogComponentRegistration,
  starterGridComponentRegistration,
  starterHeadingComponentRegistration,
  starterIconComponentRegistration,
  starterImageComponentRegistration,
  starterRadioGroupComponentRegistration,
  starterSeparatorComponentRegistration,
  starterStackComponentRegistration,
  starterSwitchComponentRegistration,
  starterTextAreaComponentRegistration,
  starterTextComponentRegistration,
  starterTextFieldComponentRegistration,
} from "./contracts.js";
export type {
  StarterButtonProps,
  StarterBoxProps,
  StarterSelectProps,
  StarterCheckboxProps,
  StarterDialogProps,
  StarterSelectOption,
  StarterGridProps,
  StarterHeadingProps,
  StarterIconProps,
  StarterImageProps,
  StarterRadioGroupOption,
  StarterRadioGroupProps,
  StarterSeparatorProps,
  StarterStackProps,
  StarterSwitchProps,
  StarterTextAreaProps,
  StarterTextProps,
  StarterTextFieldProps,
} from "./contracts.js";
export {
  createStarterNodeTemplate,
  STARTER_TEMPLATE_ID_PREFIX_MAX_LENGTH,
  STARTER_TEMPLATE_MAX_RESERVED_IDS,
} from "./templates.js";
export type {
  CreateStarterNodeTemplateInput,
  StarterSourceNode,
  StarterTemplateCapabilityId,
} from "./templates.js";
