/* global console */

import assert from "node:assert/strict";

const packageRoot = await import("../dist/index.js");

assert.deepEqual(Object.keys(packageRoot).sort(), [
  "STARTER_ACCORDION_CAPABILITY_ID",
  "STARTER_BOX_CAPABILITY_ID",
  "STARTER_BUTTON_CAPABILITY_ID",
  "STARTER_CATALOG_ID",
  "STARTER_CATALOG_TARGET",
  "STARTER_CATALOG_TEMPLATE",
  "STARTER_CATALOG_VERSION",
  "STARTER_CHECKBOX_CAPABILITY_ID",
  "STARTER_COMBOBOX_CAPABILITY_ID",
  "STARTER_COMPONENT_REGISTRATIONS",
  "STARTER_DIALOG_CAPABILITY_ID",
  "STARTER_DIALOG_CONTENT_MAX_ITEMS",
  "STARTER_DISCLOSURE_MAX_ITEMS",
  "STARTER_GRID_CAPABILITY_ID",
  "STARTER_HEADING_CAPABILITY_ID",
  "STARTER_ICON_CAPABILITY_ID",
  "STARTER_IMAGE_CAPABILITY_ID",
  "STARTER_LAYOUT_CONTENT_MAX_ITEMS",
  "STARTER_MENU_CAPABILITY_ID",
  "STARTER_NUMBER_FIELD_CAPABILITY_ID",
  "STARTER_NUMERIC_MAXIMUM",
  "STARTER_NUMERIC_MAX_STEP",
  "STARTER_NUMERIC_MINIMUM",
  "STARTER_OVERLAY_CONTENT_MAX_ITEMS",
  "STARTER_POPOVER_CAPABILITY_ID",
  "STARTER_RADIO_GROUP_CAPABILITY_ID",
  "STARTER_RADIO_GROUP_MAX_OPTIONS",
  "STARTER_SELECTION_MAX_OPTIONS",
  "STARTER_SELECT_CAPABILITY_ID",
  "STARTER_SELECT_MAX_OPTIONS",
  "STARTER_SEPARATOR_CAPABILITY_ID",
  "STARTER_SLIDER_CAPABILITY_ID",
  "STARTER_STACK_CAPABILITY_ID",
  "STARTER_SWITCH_CAPABILITY_ID",
  "STARTER_TABS_CAPABILITY_ID",
  "STARTER_TABS_MAX_ITEMS",
  "STARTER_TEMPLATE_ID_PREFIX_MAX_LENGTH",
  "STARTER_TEMPLATE_MAX_RESERVED_IDS",
  "STARTER_TEXT_AREA_CAPABILITY_ID",
  "STARTER_TEXT_CAPABILITY_ID",
  "STARTER_TEXT_FIELD_CAPABILITY_ID",
  "STARTER_TOOLTIP_CAPABILITY_ID",
  "createStarterNodeTemplate",
  "starterAccordionComponentRegistration",
  "starterBoxComponentRegistration",
  "starterButtonComponentRegistration",
  "starterCheckboxComponentRegistration",
  "starterComboboxComponentRegistration",
  "starterDialogComponentRegistration",
  "starterGridComponentRegistration",
  "starterHeadingComponentRegistration",
  "starterIconComponentRegistration",
  "starterImageComponentRegistration",
  "starterMenuComponentRegistration",
  "starterNumberFieldComponentRegistration",
  "starterPopoverComponentRegistration",
  "starterRadioGroupComponentRegistration",
  "starterSelectComponentRegistration",
  "starterSeparatorComponentRegistration",
  "starterSliderComponentRegistration",
  "starterStackComponentRegistration",
  "starterSwitchComponentRegistration",
  "starterTabsComponentRegistration",
  "starterTextAreaComponentRegistration",
  "starterTextComponentRegistration",
  "starterTextFieldComponentRegistration",
  "starterTooltipComponentRegistration",
]);

const template = packageRoot.createStarterNodeTemplate({
  capabilityId: packageRoot.STARTER_GRID_CAPABILITY_ID,
  idPrefix: "public.grid",
});
assert.equal(template.use, packageRoot.STARTER_GRID_CAPABILITY_ID);
assert.equal(template.slots.default.length, 2);
assert.equal(Object.isFrozen(template), true);
console.log("✔ built starter catalog public package exports reviewed members");
