import { createHash } from "node:crypto";
import { lstat, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { compile } from "json-schema-to-typescript";
import { format } from "prettier";

import {
  DEFAULT_SNAPSHOT_ROOT,
  EXPECTED_PROTOCOL_SNAPSHOT,
  verifyProtocolSnapshot,
} from "./protocol-snapshot-integrity.mjs";

const SCRIPT_DIRECTORY = path.dirname(fileURLToPath(import.meta.url));
const WORKSPACE_ROOT = path.resolve(SCRIPT_DIRECTORY, "../..");
const require = createRequire(import.meta.url);
const generatorRequire = createRequire(require.resolve("json-schema-to-typescript"));

/** Absolute directory containing the three frozen DESEN 0.1.0 JSON Schemas. */
export const DEFAULT_PROTOCOL_SCHEMA_DIRECTORY = path.join(DEFAULT_SNAPSHOT_ROOT, "schemas");

/** Absolute directory containing the tracked DESEN 0.1.0 generated declarations. */
export const DEFAULT_PROTOCOL_TYPES_ROOT = path.join(
  WORKSPACE_ROOT,
  "packages/protocol/src/generated/0.1.0",
);

/** Absolute path to the deterministic M02-T03 evidence artifact. */
export const DEFAULT_PROTOCOL_TYPES_ARTIFACT_PATH = path.join(
  WORKSPACE_ROOT,
  "docs/proof/artifacts/protocol-0.1.0-types.json",
);

/** Fixed root-schema and output inventory for the DESEN 0.1.0 TypeScript projection. */
export const PROTOCOL_TYPE_SCHEMA_SPECS = Object.freeze([
  Object.freeze({
    schemaFile: "desen-source.schema.json",
    schemaPath: "packages/protocol/upstream/0.1.0/snapshot/schemas/desen-source.schema.json",
    schemaId: "https://schemas.desen.dev/0.1/desen-source.schema.json",
    schemaTitle: "DESEN Design Source Document",
    internalRootName: "DESENDesignSourceDocument",
    outputFile: "desen-source.generated.ts",
    outputPath: "packages/protocol/src/generated/0.1.0/desen-source.generated.ts",
  }),
  Object.freeze({
    schemaFile: "desen-bundle.schema.json",
    schemaPath: "packages/protocol/upstream/0.1.0/snapshot/schemas/desen-bundle.schema.json",
    schemaId: "https://schemas.desen.dev/0.1/desen-bundle.schema.json",
    schemaTitle: "DESEN Published Design Bundle",
    internalRootName: "DESENPublishedDesignBundle",
    outputFile: "desen-bundle.generated.ts",
    outputPath: "packages/protocol/src/generated/0.1.0/desen-bundle.generated.ts",
  }),
  Object.freeze({
    schemaFile: "desen-catalog.schema.json",
    schemaPath: "packages/protocol/upstream/0.1.0/snapshot/schemas/desen-catalog.schema.json",
    schemaId: "https://schemas.desen.dev/0.1/desen-catalog.schema.json",
    schemaTitle: "DESEN Capability Catalog",
    internalRootName: "DESENCapabilityCatalog",
    outputFile: "desen-catalog.generated.ts",
    outputPath: "packages/protocol/src/generated/0.1.0/desen-catalog.generated.ts",
  }),
]);

const GENERATOR_NAME = "json-schema-to-typescript";
const GENERATOR_VERSION = "15.0.4";
const FORMATTER_NAME = "prettier";
const FORMATTER_VERSION = "3.9.6";
const PROJECTION_PROFILE = "desen-typescript-structural-v1";
const GENERATED_BANNER = `/* eslint-disable @typescript-eslint/consistent-indexed-object-style -- JSON Schema additionalProperties are emitted as index signatures. */
/**
 * Generated from the frozen DESEN 0.1.0 JSON Schema structural projection.
 * Do not edit this file or the frozen schema by hand.
 * Run \`pnpm generate:protocol-types\` to regenerate tracked declarations.
 * Runtime validation remains the responsibility of the validator package.
 */`;

const GENERATOR_PROFILE = Object.freeze({
  $refOptions: Object.freeze({ resolve: Object.freeze({ external: false }) }),
  additionalProperties: true,
  bannerComment: GENERATED_BANNER,
  declareExternallyReferenced: true,
  enableConstEnums: false,
  format: true,
  ignoreMinAndMaxItems: true,
  inferStringEnumKeysFromValues: false,
  maxItems: -1,
  strictIndexSignatures: false,
  style: Object.freeze({
    bracketSpacing: true,
    printWidth: 100,
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "all",
    useTabs: false,
  }),
  unknownAny: true,
  unreachableDefinitions: true,
});

const PROJECTION_RULES = Object.freeze([
  Object.freeze({
    schemas: Object.freeze(["desen-source.schema.json", "desen-bundle.schema.json"]),
    pointer: "#/$defs/predicateSpec/allOf",
    action: "omit-validator-only-conditional-cardinality",
  }),
  Object.freeze({
    schemas: Object.freeze(["desen-source.schema.json", "desen-bundle.schema.json"]),
    pointer: "#/$defs/variantSpec/anyOf",
    action: "distribute-required-union-over-object",
  }),
  Object.freeze({
    schemas: Object.freeze(["desen-catalog.schema.json"]),
    pointer: "#/$defs/behaviorCapability/properties/attachTo/anyOf",
    action: "distribute-required-union-over-object",
  }),
]);

const PUBLIC_EXPORTS = Object.freeze(["DesenSource", "DesenBundle", "DesenCatalog"]);

const LIMITATIONS = Object.freeze([
  "These declarations are a compile-time structural projection, not runtime validation of untrusted input.",
  "TypeScript does not enforce JSON Schema patterns, formats, uniqueness, property-name rules, or general numeric, string, array, and object cardinality constraints.",
  "Predicate argument cardinality expressed with if/then remains owned by semantic validation and is deliberately omitted from this projection.",
  "TypeScript unions do not prove JSON Schema oneOf exclusivity, and index signatures cannot express every additionalProperties interaction.",
  "Schema defaults are annotations only; generation does not add or mutate document values.",
  "Public aliases reject functions, undefined, bigint, and symbols in unconstrained positions, but TypeScript cannot distinguish finite JSON numbers from NaN or Infinity.",
]);

/** Stable internal failure raised by DESEN protocol type generation and drift verification. */
export class ProtocolTypesError extends Error {
  /**
   * @param {string} code stable internal failure code
   * @param {string} message human-readable failure summary
   * @param {Record<string, unknown>} [details] structured diagnostic context
   */
  constructor(code, message, details = {}) {
    super(message);
    this.name = "ProtocolTypesError";
    this.code = code;
    this.details = details;
  }
}

function fail(code, message, details = {}) {
  throw new ProtocolTypesError(code, message, details);
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function stableJson(value) {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`;
  if (value !== null && typeof value === "object") {
    return `{${Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${stableJson(value[key])}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}

function compareByteMaps(left, right) {
  if (left.size !== right.size) return false;
  for (const [key, value] of left) {
    const candidate = right.get(key);
    if (candidate === undefined || !Buffer.from(value).equals(Buffer.from(candidate))) return false;
  }
  return true;
}

function assertPlainObject(value, pointer) {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    fail("TYPE_PROJECTION_INVARIANT", "A projection target is not the expected object schema.", {
      pointer,
    });
  }
}

function omitPredicateCardinality(schema, schemaFile) {
  const pointer = "#/$defs/predicateSpec/allOf";
  const predicate = schema.$defs?.predicateSpec;
  assertPlainObject(predicate, pointer);
  const refinements = predicate.allOf;
  if (
    !Array.isArray(refinements) ||
    refinements.length !== 3 ||
    refinements.some((refinement) => {
      if (refinement === null || typeof refinement !== "object" || Array.isArray(refinement)) {
        return true;
      }
      const keys = Object.keys(refinement).sort();
      return keys.length !== 2 || keys[0] !== "if" || keys[1] !== "then";
    })
  ) {
    fail(
      "TYPE_PROJECTION_INVARIANT",
      "Predicate conditional cardinality no longer matches the reviewed projection rule.",
      { schemaFile, pointer },
    );
  }
  delete predicate.allOf;
}

function distributeRequiredUnion(node, schemaFile, pointer) {
  assertPlainObject(node, pointer);
  if (!Array.isArray(node.anyOf) || node.anyOf.length !== 2) {
    fail("TYPE_PROJECTION_INVARIANT", "A required-union projection changed shape.", {
      schemaFile,
      pointer,
    });
  }

  const branches = node.anyOf.map((branch) => {
    assertPlainObject(branch, pointer);
    if (
      Object.keys(branch).length !== 1 ||
      !Array.isArray(branch.required) ||
      branch.required.length !== 1 ||
      typeof branch.required[0] !== "string"
    ) {
      fail(
        "TYPE_PROJECTION_INVARIANT",
        "A required-union branch contains semantics not covered by the projection rule.",
        { schemaFile, pointer },
      );
    }
    return branch.required[0];
  });

  const base = structuredClone(node);
  delete base.anyOf;
  const baseRequired = Array.isArray(base.required) ? base.required : [];
  return {
    anyOf: branches.map((requiredProperty) => ({
      ...structuredClone(base),
      required: [...new Set([...baseRequired, requiredProperty])],
    })),
  };
}

function projectSchema(schema, schemaFile) {
  const projection = structuredClone(schema);
  const transformations = [];

  if (schemaFile === "desen-source.schema.json" || schemaFile === "desen-bundle.schema.json") {
    omitPredicateCardinality(projection, schemaFile);
    transformations.push(PROJECTION_RULES[0]);

    const variantPointer = "#/$defs/variantSpec/anyOf";
    projection.$defs.variantSpec = distributeRequiredUnion(
      projection.$defs?.variantSpec,
      schemaFile,
      variantPointer,
    );
    transformations.push(PROJECTION_RULES[1]);
  } else if (schemaFile === "desen-catalog.schema.json") {
    const attachToPointer = "#/$defs/behaviorCapability/properties/attachTo/anyOf";
    projection.$defs.behaviorCapability.properties.attachTo = distributeRequiredUnion(
      projection.$defs?.behaviorCapability?.properties?.attachTo,
      schemaFile,
      attachToPointer,
    );
    transformations.push(PROJECTION_RULES[2]);
  } else {
    fail("TYPE_SCHEMA_INVENTORY_MISMATCH", "An unrecognized schema reached type projection.", {
      schemaFile,
    });
  }

  return { projection, transformations };
}

function assertToolVersions() {
  const installedGeneratorVersion = require("json-schema-to-typescript/package.json").version;
  const installedFormatterVersion = generatorRequire("prettier/package.json").version;
  if (
    installedGeneratorVersion !== GENERATOR_VERSION ||
    installedFormatterVersion !== FORMATTER_VERSION
  ) {
    fail("TYPE_TOOL_VERSION_MISMATCH", "The installed type-generation tools are not pinned.", {
      expected: {
        generator: GENERATOR_VERSION,
        formatter: FORMATTER_VERSION,
      },
      actual: {
        generator: installedGeneratorVersion,
        formatter: installedFormatterVersion,
      },
    });
  }
}

function assertGeneratedContract(output, spec) {
  const violations = [];
  if (!output.includes(`export interface ${spec.internalRootName}`)) {
    violations.push("missing-root-declaration");
  }
  if (/(?<!["'])\bany\b(?!["'])/.test(output)) violations.push("forbidden-any");
  if (/\b(?:const\s+)?enum\b/.test(output)) violations.push("runtime-enum");
  if (output.includes("undefined[]")) violations.push("recursive-array-regression");
  if (
    spec.schemaFile !== "desen-catalog.schema.json" &&
    (!output.includes("ValueSpec[]") || !output.includes("export interface PredicateSpec"))
  ) {
    violations.push("recursive-or-closed-structural-projection-missing");
  }
  if (violations.length > 0) {
    fail(
      "TYPE_GENERATION_CONTRACT_VIOLATION",
      "Generated declarations violate their safety profile.",
      {
        schemaFile: spec.schemaFile,
        violations,
      },
    );
  }
}

/**
 * Loads the exact three frozen schema files without changing or normalizing their bytes.
 *
 * @param {string} [schemaDirectory] alternate canonical-layout directory for tests
 * @returns {Promise<Map<string, Buffer>>}
 */
export async function loadProtocolTypeSchemaFiles(
  schemaDirectory = DEFAULT_PROTOCOL_SCHEMA_DIRECTORY,
) {
  const schemaFiles = new Map();
  for (const spec of PROTOCOL_TYPE_SCHEMA_SPECS) {
    schemaFiles.set(spec.schemaFile, await readFile(path.join(schemaDirectory, spec.schemaFile)));
  }
  return schemaFiles;
}

function validateSchemaInventory(schemaFiles) {
  const expected = PROTOCOL_TYPE_SCHEMA_SPECS.map((spec) => spec.schemaFile).sort();
  const actual = [...schemaFiles.keys()].sort();
  const missing = expected.filter((schemaFile) => !actual.includes(schemaFile));
  const unexpected = actual.filter((schemaFile) => !expected.includes(schemaFile));
  if (missing.length > 0 || unexpected.length > 0) {
    fail("TYPE_SCHEMA_INVENTORY_MISMATCH", "The type generator received the wrong schema roots.", {
      missing,
      unexpected,
    });
  }
}

function buildAggregateOutputSha256(outputFacts) {
  const aggregate = createHash("sha256");
  for (const output of [...outputFacts].sort((left, right) =>
    left.path < right.path ? -1 : left.path > right.path ? 1 : 0,
  )) {
    aggregate.update(`${output.path}\0${output.sha256}\n`, "utf8");
  }
  return aggregate.digest("hex");
}

function buildEvidence(inputs, outputs) {
  const outputFacts = PROTOCOL_TYPE_SCHEMA_SPECS.map((spec) => {
    const bytes = outputs.get(spec.outputFile);
    return {
      path: spec.outputPath,
      sha256: sha256(bytes),
      bytes: bytes.byteLength,
      internalRootName: spec.internalRootName,
    };
  });
  return {
    schemaVersion: 1,
    task: "M02-T03",
    result: "PASS",
    lastVerified: "2026-07-21",
    claim:
      "Three internal TypeScript root types are deterministically derived from the frozen DESEN 0.1.0 JSON Schemas.",
    protocol: EXPECTED_PROTOCOL_SNAPSHOT.protocol,
    source: {
      commit: EXPECTED_PROTOCOL_SNAPSHOT.sourceCommit,
      tree: EXPECTED_PROTOCOL_SNAPSHOT.sourceTree,
      snapshotAggregateSha256: EXPECTED_PROTOCOL_SNAPSHOT.aggregateSha256,
    },
    generator: {
      package: GENERATOR_NAME,
      version: GENERATOR_VERSION,
      formatter: { package: FORMATTER_NAME, version: FORMATTER_VERSION },
      optionsHash: sha256(stableJson(GENERATOR_PROFILE)),
      options: GENERATOR_PROFILE,
      projectionProfile: PROJECTION_PROFILE,
      projectionRules: PROJECTION_RULES,
    },
    inputs,
    outputs: outputFacts,
    publicExports: PUBLIC_EXPORTS,
    publicTypeProjection: {
      profile: "desen-json-value-v1",
      rule: "Recursively narrow generator unknown positions to JSON-compatible TypeScript values.",
    },
    coverage: {
      schemaRoots: PROTOCOL_TYPE_SCHEMA_SPECS.length,
      generatedRoots: outputFacts.length,
      missing: 0,
      unexpected: 0,
      byteDrift: 0,
    },
    aggregateOutputSha256: buildAggregateOutputSha256(outputFacts),
    aggregateFormula: "sha256(sorted(outputPath + NUL + sha256(outputBytes) + LF))",
    verificationCommand: "pnpm verify:protocol-types",
    testCommand: "pnpm test:protocol-types",
    compileTimeCommand: "pnpm --filter @desen/protocol typecheck",
    limitations: LIMITATIONS,
  };
}

/**
 * Generates the complete in-memory DESEN 0.1.0 declaration set and deterministic evidence.
 *
 * Frozen input bytes are never written. Tests may inject an exact-name schema map to prove drift
 * detection without mutating the canonical snapshot.
 *
 * @param {{ schemaFiles?: Map<string, Uint8Array | string> }} [options] generation inputs
 */
export async function generateProtocolTypes({ schemaFiles } = {}) {
  assertToolVersions();
  const inputsByName = schemaFiles ?? (await loadProtocolTypeSchemaFiles());
  validateSchemaInventory(inputsByName);

  const inputs = [];
  const outputs = new Map();
  for (const spec of PROTOCOL_TYPE_SCHEMA_SPECS) {
    const schemaBytes = Buffer.from(inputsByName.get(spec.schemaFile));
    let schema;
    try {
      schema = JSON.parse(schemaBytes.toString("utf8"));
    } catch (error) {
      fail("TYPE_SCHEMA_PARSE_FAILED", "A frozen schema is not valid JSON.", {
        schemaFile: spec.schemaFile,
        cause: String(error),
      });
    }
    if (schema.$id !== spec.schemaId) {
      fail("TYPE_SCHEMA_ID_MISMATCH", "A schema root has an unexpected $id.", {
        schemaFile: spec.schemaFile,
        expected: spec.schemaId,
        actual: schema.$id,
      });
    }
    if (schema.title !== spec.schemaTitle) {
      fail("TYPE_SCHEMA_TITLE_MISMATCH", "A schema root has an unexpected title.", {
        schemaFile: spec.schemaFile,
        expected: spec.schemaTitle,
        actual: schema.title,
      });
    }

    const { projection, transformations } = projectSchema(schema, spec.schemaFile);
    let generated;
    try {
      generated = await compile(projection, spec.internalRootName, {
        ...GENERATOR_PROFILE,
        cwd: DEFAULT_PROTOCOL_SCHEMA_DIRECTORY,
      });
    } catch (error) {
      fail("TYPE_GENERATION_FAILED", "Type generation failed for a frozen schema root.", {
        schemaFile: spec.schemaFile,
        cause: String(error),
      });
    }
    const normalized = `${generated.replaceAll("\r\n", "\n").trimEnd()}\n`;
    assertGeneratedContract(normalized, spec);
    const outputBytes = Buffer.from(normalized, "utf8");
    outputs.set(spec.outputFile, outputBytes);
    inputs.push({
      path: spec.schemaPath,
      $id: schema.$id,
      title: schema.title,
      sha256: sha256(schemaBytes),
      bytes: schemaBytes.byteLength,
      internalRootName: spec.internalRootName,
      outputPath: spec.outputPath,
      projectionTransformations: transformations.map(({ pointer, action }) => ({
        pointer,
        action,
      })),
    });
  }

  const evidence = buildEvidence(inputs, outputs);
  const artifactText = await format(JSON.stringify(evidence), {
    endOfLine: "lf",
    parser: "json",
    printWidth: 100,
    tabWidth: 2,
    trailingComma: "all",
  });
  const artifactBytes = Buffer.from(artifactText, "utf8");
  return Object.freeze({ outputs, evidence, artifactBytes });
}

async function loadGeneratedOutputs(outputRoot) {
  let rootStats;
  try {
    rootStats = await lstat(outputRoot);
  } catch (error) {
    fail("TYPE_OUTPUT_ROOT_MISSING", "The tracked generated-type directory is missing.", {
      cause: String(error),
    });
  }
  if (!rootStats.isDirectory() || rootStats.isSymbolicLink()) {
    fail("TYPE_OUTPUT_UNSUPPORTED_ENTRY", "The generated-type root must be a real directory.");
  }

  const outputs = new Map();
  const entries = (await readdir(outputRoot, { withFileTypes: true })).sort((left, right) =>
    left.name < right.name ? -1 : left.name > right.name ? 1 : 0,
  );
  for (const entry of entries) {
    if (!entry.isFile()) {
      fail(
        "TYPE_OUTPUT_UNSUPPORTED_ENTRY",
        "Generated declarations may not contain directories, symlinks, or special entries.",
        { path: entry.name },
      );
    }
    outputs.set(entry.name, await readFile(path.join(outputRoot, entry.name)));
  }
  return outputs;
}

function normalizeInjectedOutputs(generatedFiles) {
  return new Map(
    [...generatedFiles].map(([fileName, value]) => [fileName, Buffer.from(value, "utf8")]),
  );
}

function verifyOutputInventory(expected, actual) {
  const expectedNames = [...expected.keys()].sort();
  const actualNames = [...actual.keys()].sort();
  const missing = expectedNames.filter((fileName) => !actualNames.includes(fileName));
  const unexpected = actualNames.filter((fileName) => !expectedNames.includes(fileName));
  if (missing.length > 0 || unexpected.length > 0) {
    fail("TYPE_OUTPUT_INVENTORY_MISMATCH", "Generated declarations are missing or unexpected.", {
      missing,
      unexpected,
    });
  }
}

async function ensureRealDirectoryChain(workspaceRoot, directoryPath) {
  const resolvedWorkspaceRoot = path.resolve(workspaceRoot);
  const resolvedDirectoryPath = path.resolve(directoryPath);
  const relativePath = path.relative(resolvedWorkspaceRoot, resolvedDirectoryPath);
  if (
    path.isAbsolute(relativePath) ||
    relativePath === ".." ||
    relativePath.startsWith(`..${path.sep}`)
  ) {
    fail("TYPE_OUTPUT_PATH_ESCAPE", "A generated artifact path escapes the workspace root.", {
      path: resolvedDirectoryPath,
    });
  }

  let currentPath = resolvedWorkspaceRoot;
  const segments = relativePath === "" ? [] : relativePath.split(path.sep);
  for (const segment of ["", ...segments]) {
    if (segment !== "") currentPath = path.join(currentPath, segment);
    let stats;
    try {
      stats = await lstat(currentPath);
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
      try {
        await mkdir(currentPath);
      } catch (mkdirError) {
        if (mkdirError?.code !== "EEXIST") throw mkdirError;
      }
      stats = await lstat(currentPath);
    }
    if (!stats.isDirectory() || stats.isSymbolicLink()) {
      fail(
        "TYPE_OUTPUT_UNSUPPORTED_ENTRY",
        "Generated artifact directories must be real directories, never symlinks.",
        { path: currentPath },
      );
    }
  }

  return resolvedDirectoryPath;
}

async function assertWritableRegularTarget(targetPath) {
  try {
    const stats = await lstat(targetPath);
    if (!stats.isFile() || stats.isSymbolicLink()) {
      fail(
        "TYPE_OUTPUT_UNSUPPORTED_ENTRY",
        "Generation refuses to replace a symlink or non-regular target.",
        { path: targetPath },
      );
    }
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
}

/**
 * Writes an already generated declaration set without following workspace-internal symlinks.
 *
 * Both destination directory chains are validated before the first file write. Unexpected tracked
 * files are deliberately left in place so the subsequent read-only verifier can reject them.
 *
 * @param {{ outputs: Map<string, Uint8Array | string>; artifactBytes: Uint8Array | string }} generated deterministic generation result
 * @param {{ workspaceRoot?: string; outputRoot?: string; artifactPath?: string }} [options] alternate safe paths used by negative tests
 */
export async function writeProtocolTypeArtifacts(
  generated,
  {
    workspaceRoot = WORKSPACE_ROOT,
    outputRoot = DEFAULT_PROTOCOL_TYPES_ROOT,
    artifactPath = DEFAULT_PROTOCOL_TYPES_ARTIFACT_PATH,
  } = {},
) {
  const expectedInventory = new Map(
    PROTOCOL_TYPE_SCHEMA_SPECS.map((spec) => [spec.outputFile, Buffer.alloc(0)]),
  );
  verifyOutputInventory(expectedInventory, generated.outputs);

  const safeOutputRoot = await ensureRealDirectoryChain(workspaceRoot, outputRoot);
  const safeArtifactRoot = await ensureRealDirectoryChain(
    workspaceRoot,
    path.dirname(artifactPath),
  );
  const safeArtifactPath = path.join(safeArtifactRoot, path.basename(artifactPath));

  for (const spec of PROTOCOL_TYPE_SCHEMA_SPECS) {
    const targetPath = path.join(safeOutputRoot, spec.outputFile);
    await assertWritableRegularTarget(targetPath);
  }
  await assertWritableRegularTarget(safeArtifactPath);

  for (const spec of PROTOCOL_TYPE_SCHEMA_SPECS) {
    await writeFile(
      path.join(safeOutputRoot, spec.outputFile),
      generated.outputs.get(spec.outputFile),
    );
  }
  await writeFile(safeArtifactPath, generated.artifactBytes);

  return Object.freeze({ outputRoot: safeOutputRoot, artifactPath: safeArtifactPath });
}

/**
 * Read-only verification of snapshot integrity, deterministic regeneration, tracked outputs, and
 * the M02-T03 evidence artifact.
 *
 * @param {{
 *   schemaFiles?: Map<string, Uint8Array | string>;
 *   generatedFiles?: Map<string, Uint8Array | string>;
 *   outputRoot?: string;
 *   artifactBytes?: Uint8Array | string;
 *   artifactPath?: string;
 *   verifyArtifact?: boolean;
 *   verifySnapshot?: boolean;
 * }} [options] alternate inputs used by negative tests
 */
export async function verifyProtocolTypes({
  schemaFiles,
  generatedFiles,
  outputRoot = DEFAULT_PROTOCOL_TYPES_ROOT,
  artifactBytes,
  artifactPath = DEFAULT_PROTOCOL_TYPES_ARTIFACT_PATH,
  verifyArtifact = true,
  verifySnapshot = true,
} = {}) {
  if (verifySnapshot) await verifyProtocolSnapshot();

  const first = await generateProtocolTypes({ schemaFiles });
  const second = await generateProtocolTypes({ schemaFiles });
  if (
    !compareByteMaps(first.outputs, second.outputs) ||
    !first.artifactBytes.equals(second.artifactBytes)
  ) {
    fail("TYPE_GENERATION_NONDETERMINISTIC", "Independent type generations differ in bytes.");
  }

  const actualOutputs =
    generatedFiles === undefined
      ? await loadGeneratedOutputs(outputRoot)
      : normalizeInjectedOutputs(generatedFiles);
  verifyOutputInventory(first.outputs, actualOutputs);
  for (const [fileName, expectedBytes] of first.outputs) {
    const actualBytes = actualOutputs.get(fileName);
    if (!expectedBytes.equals(actualBytes)) {
      fail("TYPE_OUTPUT_DRIFT", "A tracked declaration differs from deterministic regeneration.", {
        path: fileName,
        expected: sha256(expectedBytes),
        actual: sha256(actualBytes),
      });
    }
  }

  if (verifyArtifact) {
    let actualArtifactBytes;
    try {
      actualArtifactBytes =
        artifactBytes === undefined ? await readFile(artifactPath) : Buffer.from(artifactBytes);
    } catch (error) {
      fail("TYPE_ARTIFACT_MISSING", "The M02-T03 evidence artifact is missing.", {
        cause: String(error),
      });
    }
    if (!first.artifactBytes.equals(actualArtifactBytes)) {
      fail("TYPE_ARTIFACT_DRIFT", "The M02-T03 evidence artifact is stale or modified.", {
        expected: sha256(first.artifactBytes),
        actual: sha256(actualArtifactBytes),
      });
    }
  }

  return Object.freeze({
    result: "PASS",
    protocol: EXPECTED_PROTOCOL_SNAPSHOT.protocol,
    schemaRoots: PROTOCOL_TYPE_SCHEMA_SPECS.length,
    generatedRoots: first.outputs.size,
    publicExports: PUBLIC_EXPORTS,
    aggregateOutputSha256: first.evidence.aggregateOutputSha256,
    artifactSha256: sha256(first.artifactBytes),
  });
}
